stages:
  01_featurise:
    cmd: python -m rdvc_demo_project.stages.01_featurise
    params:
    - split
    - features
    outs:
    - data/featurised

  02_train:
    cmd: python -m rdvc_demo_project.stages.02_train
    deps:
    - data/featurised
    params:
    - model
    plots:
    - metrics/train/plots:
        cache: false
        x: step
metrics:
- metrics/train/metrics.json
plots:
- metrics/train/plots/metrics:
    x: step
