split:
  name: shuffle_split
  presets:
    train_fraction: 0.8
    validation_fraction: 0.0
    test_fraction: 0.2
features:
  name: morgan
  config:
    radius: 3
    n_bits: 2048
model:
  name: lightning_mlp_regressor
  config:
    x_features:
    - smiles::morgan
    y_features:
    - log_solubility
    input_dim: 2048
    hidden_dim: 128
    num_layers: 2
    num_tasks: 1
    trainer:
      accelerator: cpu
      logger:
        name: DVCLiveLogger
        config:
          dir: metrics/train
      max_epochs: 1
    datamodule:
      train:
        batch_size: 16
    optimizer:
      name: Adam
      config:
        lr: 0.0003
